
import sys

def draw_result_table_v(file_name, caption, results):
    # vertical
    f = open(file_name, 'w')
    f.write('\\begin{table}[htbp]' + '\n')
    f.write('\\caption{%s}'%(caption) + '\n')
    f.write('\\begin{adjustbox}{width=\\columnwidth}' + '\n')
    
    # symbol = 'cc|' + 'r' * (len(metrics) + 1)
    symbol = 'cc|' + 'r' * (len(metrics))
    f.write('\\begin{tabular}{%s}'%symbol + '\n')
    f.write('\\toprule' + '\n')
    f.write('\\multicolumn{2}{c|}{Model}')
    for i in range(len(metrics)):
        f.write('&')
        f.write(metrics[i])
    # f.write('&Pattern Ratio')
    f.write('\\\\\n')
    for i in range(len(model_names)):
        f.write('\\midrule' + '\n')
        f.write('\\multirow{%s}{*}{%s}'%(len(typees), tex_model_names[i]))
        for j in range(len(typees)):
            if j != 0:
                f.write('~')
            f.write('&%s'%typees[j])
            for each in results[model_names[i]][typees[j]]:
                f.write('&%.2f'%each)
            # f.write('&%.2f'%pattern_data[i * len(typees) + j])
            f.write('\\\\\n')
    f.write('\\bottomrule' + '\n')
    f.write('\\end{tabular}' + '\n')
    f.write('\\end{adjustbox}' + '\n')
    f.write('\\end{table}' + '\n')
    f.close()


if __name__ == '__main__':
    data_file_name = '../CommitMessages/metrics_mark_code'
    tex_flle_name = 'TablesAndFigures/rq3_table5.tex'
    pattern_data = [float(x.strip()) for x in open('../Patterns/patterns_mark_code') if x.strip()]
    results = {}
    model_names = ['NMT', 'PtrGNCMsg', 'CODISUM', 'CoreGen', 'FIRA']
    tex_model_names = ['\\nmt{}', '\\ptrgn{}', '\\codisum{}', '\\coregen{}', '\\fira{}']
    typees = ['Code\&Mark', 'Only Mark']
    metrics = ['BLEU', 'ROUGE-L', 'METEOR']
    for model_name in model_names:
        results[model_name] = {}
        for typee in typees:
            results[model_name][typee] = []
    data = [float(x.strip()) for x in open(data_file_name, 'r') if x.strip()]
    for i in range(len(metrics)):
        for j in range(len(model_names)):
            for k in range(len(typees)):
                results[model_names[j]][typees[k]].append(data[i * len(model_names) * len(typees) + j * len(typees) + k])
    caption = '\\label{tab:code_mark}Metrics and pattern ratio of commit messages generated by models training by different input representation'

    draw_result_table_v(tex_flle_name, caption, results)